language: rust
sudo: required
dist: trusty
cache: cargo

matrix:
  include:
    - name: "stable + debug"
      rust: stable
      script:
      - sh run_benches_stable_debug.sh
      - cargo test -- --nocapture

    - name: "stable + release"
      rust: stable
      script:
      - sh run_benches_stable_release.sh
      - cargo test -- --nocapture

    - name: "nightly + debug"
      rust: nightly
      script:
      - sh run_benches_nightly_debug.sh
      - cargo test -- --nocapture

    - name: "nightly + release"
      rust: nightly
      script:
      - sh run_benches_nightly_release.sh
      - cargo test -- --nocapture