language: rust
sudo: required
dist: trusty
cache: cargo

matrix:
  
  allow_failures:
    - env: 'OPT-LEVEL=0'
  
  include:
    # -C opt-level = 0
    - name: "stable + debug + -C opt-level = 0"
      rust: stable
      env: 'OPT-LEVEL=0'
      script:
        - cargo clean
        - sh run_benches_stable_debug.sh opt-level=0
        - cargo test -- --nocapture

    - name: "stable + release + -C opt-level = 0"
      rust: stable
      env: 'OPT-LEVEL=0'
      script:
        - cargo clean
        - sh run_benches_stable_release.sh opt-level=0
        - cargo test -- --nocapture

    - name: "nightly + debug + -C opt-level = 0"
      rust: nightly
      env: 'OPT-LEVEL=0'
      script:
        - cargo clean
        - sh run_benches_nightly_debug.sh opt-level=0
        - cargo test -- --nocapture

    - name: "nightly + release + -C opt-level = 0"
      rust: nightly
      env: 'OPT-LEVEL=0'
      script:
        - cargo clean
        - sh run_benches_nightly_release.sh opt-level=0
        - cargo test -- --nocapture

  # -C opt-level = 1
    - name: "stable + debug + -C opt-level = 1"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_debug.sh opt-level=1
        - cargo test -- --nocapture

    - name: "stable + release + -C opt-level = 1"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_release.sh opt-level=1
        - cargo test -- --nocapture

    - name: "nightly + debug + -C opt-level = 1"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_debug.sh opt-level=1
        - cargo test -- --nocapture

    - name: "nightly + release + -C opt-level = 1"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_release.sh opt-level=1
        - cargo test -- --nocapture

  # -C opt-level = 2
    - name: "stable + debug + -C opt-level = 2"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_debug.sh opt-level=2
        - cargo test -- --nocapture

    - name: "stable + release + -C opt-level = 2"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_release.sh opt-level=2
        - cargo test -- --nocapture

    - name: "nightly + debug + -C opt-level = 2"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_debug.sh opt-level=2
        - cargo test -- --nocapture

    - name: "nightly + release + -C opt-level = 2"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_release.sh opt-level=2
        - cargo test -- --nocapture

  # -C opt-level = 3
    - name: "stable + debug + -C opt-level = 3"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_debug.sh opt-level=3
        - cargo test -- --nocapture

    - name: "stable + release + -C opt-level = 3"
      rust: stable
      script:
        - cargo clean
        - sh run_benches_stable_release.sh opt-level=3
        - cargo test -- --nocapture

    - name: "nightly + debug + -C opt-level = 3"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_debug.sh opt-level=3
        - cargo test -- --nocapture

    - name: "nightly + release + -C opt-level = 3"
      rust: nightly
      script:
        - cargo clean
        - sh run_benches_nightly_release.sh opt-level=3
        - cargo test -- --nocapture