language: rust
sudo: required
dist: trusty
cache: cargo

matrix:
  allow_failures:
    - env: OPT_LEVEL_0 = 0

  include:
    - name: "stable + debug"
      rust: stable
      env: OPT_LEVEL = 0
      script:
      - sh run_benches_stable_debug.sh $OPT_LEVEL
      - cargo test -- --nocapture

    - name: "stable + release"
      rust: stable
      env: OPT_LEVEL = 0
      script:
      - sh run_benches_stable_release.sh $OPT_LEVEL
      - cargo test -- --nocapture

    - name: "nightly + debug"
      rust: nightly
      env: OPT_LEVEL = 0
      script:
      - sh run_benches_nightly_debug.sh $OPT_LEVEL
      - cargo test -- --nocapture

    - name: "nightly + release"
      rust: nightly
      env: OPT_LEVEL = 0
      script:
      - sh run_benches_nightly_release.sh $OPT_LEVEL
      - cargo test -- --nocapture