language: rust
sudo: required
dist: trusty
cache: cargo

matrix:
  include:
    - rust: stable
      script:
      - sh run_benches_stable.sh
      - cargo test -- --nocapture

    - rust: nightly
      script:
        - sh run_benches_nightly.sh
        - cargo test -- --nocapture
