language: rust
sudo: required
cache: cargo
dist: trusty

matrix:
  
  allow_failures:
    - env: 'OPT-LEVEL=0'
    - env: 'BUILD=debug'
  
  include:
    # -C opt-level = 0
    - name: "[DEBUG] stable + nightly + -C opt-level = 0"
      env: 'OPT-LEVEL=0'
      script:
        - sh run_benches_debug.sh opt-level=0 x86_64-unknown-linux-gnu

    - name: "[RELEASE] stable + nightly + -C opt-level = 0"
      rust: stable
      env: 'OPT-LEVEL=0'
      script:
        - sh run_benches_release.sh opt-level=0 x86_64-unknown-linux-gnu

  # -C opt-level = 1
    - name: "[DEBUG] stable + nightly + -C opt-level = 1"
      env: 'BUILD=debug'
      script:
        - sh run_benches_debug.sh opt-level=1 x86_64-unknown-linux-gnu

    - name: "[RELEASE] stable + nightly + -C opt-level = 1"
      script:
        - sh run_benches_release.sh opt-level=1 x86_64-unknown-linux-gnu
    
    - name: "[RELEASE] stable + nightly + -C opt-level = 1"
      os: osx
      script:
        - sh run_benches_release.sh opt-level=1 x86_64-apple-darwin

  # -C opt-level = 2
    - name: "[DEBUG] stable + nightly + -C opt-level = 2"
      env: 'BUILD=debug'
      script:
        - sh run_benches_debug.sh opt-level=2 x86_64-unknown-linux-gnu

    - name: "[RELEASE] stable + nightly + -C opt-level = 2"
      script:
        - sh run_benches_release.sh opt-level=2 x86_64-unknown-linux-gnu
    
    - name: "[RELEASE] stable + nightly + -C opt-level = 2"
      os: osx
      script:
        - sh run_benches_release.sh opt-level=2 x86_64-apple-darwin

  # -C opt-level = 3
    - name: "[DEBUG] stable + nightly + -C opt-level = 3"
      env: 'BUILD=debug'
      script:
        - sh run_benches_debug.sh opt-level=3 x86_64-unknown-linux-gnu

    - name: "[RELEASE] stable + nightly + -C opt-level = 3"
      script:
        - sh run_benches_release.sh opt-level=3 x86_64-unknown-linux-gnu
    
    - name: "[RELEASE] stable + nightly + -C opt-level = 3"
      os: osx
      script:
        - sh run_benches_release.sh opt-level=3 x86_64-apple-darwin

install:
  - rustup toolchain install nightly
  - rustup toolchain install stable-x86_64-unknown-linux-gnu
  - rustup toolchain install nightly-x86_64-unknown-linux-gnu
  - rustup toolchain install stable-x86_64-apple-darwin
  - rustup toolchain install nightly-x86_64-apple-darwin