[package]
name = "orion-dudect"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

[dependencies]
dudect-bencher = "0.3.0"
rand = "0.3"
orion = { git = "https://github.com/brycx/orion/" }
clap = "2.25"
ctrlc = "3.0"
regex = "1"
constant_time_eq = "0.1.3"
subtle = "2"

[features]
nightly = [ "orion/nightly" ]

[[bin]]
name = "orion"
path = "ct-bencher/orion.rs"

[[bin]]
name = "subtle"
path = "ct-bencher/subtle.rs"

[[bin]]
name = "custom"
path = "ct-bencher/custom.rs"

[[bin]]
name = "constant_time_eq"
path = "ct-bencher/constant_time_eq.rs"