[package]
name = "orion-dudect"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

[dependencies]
dudect-bencher = "0.4.1"
rand = "0.7"
orion = { git = "https://github.com/brycx/orion/", branch = "master" }
clap = "2.33"
ctrlc = "3.1"
regex = "1"
rand_chacha = "0.2.1"

[features]
nightly = [ "orion/nightly" ]

[[bin]]
name = "secure_cmp"
path = "ct-bencher/secure_cmp.rs"

[[bin]]
name = "poly1305"
path = "ct-bencher/poly1305.rs"

[[bin]]
name = "newtype"
path = "ct-bencher/newtype.rs"