[package]
name = "orion-dudect"
version = "0.1.0"
authors = ["brycx <brycx@protonmail.com>"]
edition = "2018"

[dependencies]
dudect-bencher = "0.3.0"
rand = "0.3"
clap = "2.25"
ctrlc = "3.0"
regex = "1"
subtle = "2"

[features]
nightly = [ "subtle/nightly" ]

[[bin]]
name = "subtle_from"
path = "ct-bencher/subtle_from.rs"

[[bin]]
name = "subtle"
path = "ct-bencher/subtle.rs"