name: Weekly tests
on:
  schedule:
    - cron: '0 0 * * 0' # Midnight of each sunday

jobs:
  tests:
    strategy:
      matrix:
        rust:
          - stable
          - nightly
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      
      - name: -C opt-level = 1
        run: sh run_benches_release.sh opt-level=1

      - name: -C opt-level = 2
        run: sh run_benches_release.sh opt-level=2

      - name: -C opt-level = 3
        run: sh run_benches_release.sh opt-level=3